/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jwztqagxfkgbvyynbjgu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3enRxYWd4ZmtnYnZ5eW5iamd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4OTQ4NTYsImV4cCI6MjA4ODQ3MDg1Nn0.Edu0aqlN9ZW6b9pcGN27e3-kur3Pe8xJIQT6-7-tRcU"